services:
  timetables-postgres:
    env_file:
      - .env
    image: postgres:16-alpine
    restart: unless-stopped
    user: postgres
    volumes:
      - timetables-db-data:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  timetables-migrations:
    env_file:
      - .env
    build:
      context: timetables
      target: migrate-builder
    depends_on:
      timetables-postgres:
        condition: service_healthy
    command: >
      sh -c 'goose -dir /src/migrations postgres
      "postgres://$$POSTGRES_USER:$$POSTGRES_PASSWORD@$$POSTGRES_HOST:$$POSTGRES_PORT/$$POSTGRES_DB?sslmode=disable" up'

  timetables-backend:
    env_file:
      - .env
    build:
      context: timetables
      target: final
    expose:
      - 8466
    depends_on:
      timetables-postgres:
        condition: service_healthy
      timetables-migrations:
        condition: service_completed_successfully
    restart: unless-stopped

  timetables-nginx:
    env_file:
      - .env
    build:
      context: frontend
    ports:
      - "8470:8470"
    depends_on:
      - timetables-backend
    restart: unless-stopped

volumes:
  timetables-db-data: