// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createStagingTables = `-- name: CreateStagingTables :exec
SELECT create_staging_tables()
`

func (q *Queries) CreateStagingTables(ctx context.Context) error {
	_, err := q.db.Exec(ctx, createStagingTables)
	return err
}

const flushStagingToMain = `-- name: FlushStagingToMain :exec
SELECT flush_staging_to_main()
`

func (q *Queries) FlushStagingToMain(ctx context.Context) error {
	_, err := q.db.Exec(ctx, flushStagingToMain)
	return err
}

type InsertStagingLessonsParams struct {
	StagingID  uuid.UUID
	Subject    string
	Category   string
	Day        int32
	TimeStart  int32
	TimeEnd    int32
	RepeatRule int32
	Timetable  string
}

type InsertStagingSubgroupsAssignmentsParams struct {
	StagingID uuid.UUID
	Subgroup  string
}

type InsertStagingTeacherLocationAssignmentsParams struct {
	StagingID uuid.UUID
	Teacher   string
	Location  string
}

const updateStagingHash = `-- name: UpdateStagingHash :exec
SELECT update_staging_hash()
`

func (q *Queries) UpdateStagingHash(ctx context.Context) error {
	_, err := q.db.Exec(ctx, updateStagingHash)
	return err
}
