// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const assignSubgroupToLesson = `-- name: AssignSubgroupToLesson :exec
INSERT INTO subgroups_assignments (lesson_id, subgroup_id)
VALUES ($1, $2) ON CONFLICT (lesson_id, subgroup_id) DO NOTHING
`

type AssignSubgroupToLessonParams struct {
	LessonID   uuid.UUID
	SubgroupID int32
}

func (q *Queries) AssignSubgroupToLesson(ctx context.Context, arg AssignSubgroupToLessonParams) error {
	_, err := q.db.Exec(ctx, assignSubgroupToLesson, arg.LessonID, arg.SubgroupID)
	return err
}

const assignTeacherLocationToLesson = `-- name: AssignTeacherLocationToLesson :exec
INSERT INTO teacher_location_assignments (lesson_id, teacher_id, location_id)
VALUES ($1, $2,
        $3) ON CONFLICT (lesson_id, teacher_id, location_id) DO NOTHING
`

type AssignTeacherLocationToLessonParams struct {
	LessonID   uuid.UUID
	TeacherID  int32
	LocationID int32
}

func (q *Queries) AssignTeacherLocationToLesson(ctx context.Context, arg AssignTeacherLocationToLessonParams) error {
	_, err := q.db.Exec(ctx, assignTeacherLocationToLesson, arg.LessonID, arg.TeacherID, arg.LocationID)
	return err
}

const createLesson = `-- name: CreateLesson :one
INSERT INTO lessons (subject_id, category, day, time_start, time_end, repeat_rule, timetable_id)
VALUES ($1, $2, $3, $4,
        $5, $6, $7) RETURNING id
`

type CreateLessonParams struct {
	SubjectID   int32
	Category    string
	Day         int32
	TimeStart   int32
	TimeEnd     int32
	RepeatRule  int32
	TimetableID int32
}

func (q *Queries) CreateLesson(ctx context.Context, arg CreateLessonParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createLesson,
		arg.SubjectID,
		arg.Category,
		arg.Day,
		arg.TimeStart,
		arg.TimeEnd,
		arg.RepeatRule,
		arg.TimetableID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteLessonById = `-- name: DeleteLessonById :one
DELETE
FROM lessons
WHERE id = $1 RETURNING id
`

func (q *Queries) DeleteLessonById(ctx context.Context, lessonID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteLessonById, lessonID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteLocationById = `-- name: DeleteLocationById :one
DELETE
FROM locations
WHERE id = $1 RETURNING id, name
`

func (q *Queries) DeleteLocationById(ctx context.Context, id int32) (Location, error) {
	row := q.db.QueryRow(ctx, deleteLocationById, id)
	var i Location
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteSubgroupById = `-- name: DeleteSubgroupById :one
DELETE
FROM subgroups
WHERE id = $1 RETURNING id, name
`

func (q *Queries) DeleteSubgroupById(ctx context.Context, id int32) (Subgroup, error) {
	row := q.db.QueryRow(ctx, deleteSubgroupById, id)
	var i Subgroup
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteSubjectById = `-- name: DeleteSubjectById :one
DELETE
FROM subjects
WHERE id = $1 RETURNING id, name
`

func (q *Queries) DeleteSubjectById(ctx context.Context, id int32) (Subject, error) {
	row := q.db.QueryRow(ctx, deleteSubjectById, id)
	var i Subject
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteTeacherById = `-- name: DeleteTeacherById :one
DELETE
FROM teachers
WHERE id = $1 RETURNING id, name
`

func (q *Queries) DeleteTeacherById(ctx context.Context, id int32) (Teacher, error) {
	row := q.db.QueryRow(ctx, deleteTeacherById, id)
	var i Teacher
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteTimetableById = `-- name: DeleteTimetableById :one
DELETE
FROM timetables
WHERE id = $1 RETURNING id, name
`

type DeleteTimetableByIdRow struct {
	ID   int32
	Name string
}

func (q *Queries) DeleteTimetableById(ctx context.Context, id int32) (DeleteTimetableByIdRow, error) {
	row := q.db.QueryRow(ctx, deleteTimetableById, id)
	var i DeleteTimetableByIdRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getLessonsBySubgroupId = `-- name: GetLessonsBySubgroupId :many
SELECT id,
       subject_id,
       (SELECT name FROM subjects WHERE id = subject_id)     as subject_name,
       category,
       day,
       time_start,
       time_end,
       repeat_rule,
       timetable_id,
       (SELECT name FROM timetables WHERE id = timetable_id) as timetable_name,
       (SELECT date_start FROM timetables WHERE id = timetable_id) as timetable_date_start,
       (SELECT date_end FROM timetables WHERE id = timetable_id) as timetable_date_end
FROM lessons
         JOIN subgroups_assignments
              ON subgroups_assignments.lesson_id = id AND subgroups_assignments.subgroup_id = $1
`

type GetLessonsBySubgroupIdRow struct {
	ID                 uuid.UUID
	SubjectID          int32
	SubjectName        string
	Category           string
	Day                int32
	TimeStart          int32
	TimeEnd            int32
	RepeatRule         int32
	TimetableID        int32
	TimetableName      string
	TimetableDateStart time.Time
	TimetableDateEnd   time.Time
}

func (q *Queries) GetLessonsBySubgroupId(ctx context.Context, subgroupID int32) ([]GetLessonsBySubgroupIdRow, error) {
	rows, err := q.db.Query(ctx, getLessonsBySubgroupId, subgroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLessonsBySubgroupIdRow
	for rows.Next() {
		var i GetLessonsBySubgroupIdRow
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.SubjectName,
			&i.Category,
			&i.Day,
			&i.TimeStart,
			&i.TimeEnd,
			&i.RepeatRule,
			&i.TimetableID,
			&i.TimetableName,
			&i.TimetableDateStart,
			&i.TimetableDateEnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLocationById = `-- name: GetLocationById :one
SELECT id, name
FROM locations
WHERE id = $1
`

func (q *Queries) GetLocationById(ctx context.Context, id int32) (Location, error) {
	row := q.db.QueryRow(ctx, getLocationById, id)
	var i Location
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getLocations = `-- name: GetLocations :many
SELECT id, name
FROM locations
WHERE ($1 IS NULL OR name ILIKE '%' || $1 || '%')
ORDER BY name LIMIT $2::INTEGER
OFFSET $2::INTEGER * ($3::INTEGER)
`

type GetLocationsParams struct {
	Name     interface{}
	PageSize int32
	Page     int32
}

func (q *Queries) GetLocations(ctx context.Context, arg GetLocationsParams) ([]Location, error) {
	rows, err := q.db.Query(ctx, getLocations, arg.Name, arg.PageSize, arg.Page)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrCreateLocationByName = `-- name: GetOrCreateLocationByName :one
INSERT INTO locations (name)
VALUES ($1) ON CONFLICT (name) DO
UPDATE SET name = EXCLUDED.name
    RETURNING id
`

func (q *Queries) GetOrCreateLocationByName(ctx context.Context, name string) (int32, error) {
	row := q.db.QueryRow(ctx, getOrCreateLocationByName, name)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getOrCreateSubgroupByName = `-- name: GetOrCreateSubgroupByName :one
INSERT INTO subgroups (name)
VALUES ($1) ON CONFLICT (name) DO
UPDATE SET name = EXCLUDED.name
    RETURNING id
`

func (q *Queries) GetOrCreateSubgroupByName(ctx context.Context, name string) (int32, error) {
	row := q.db.QueryRow(ctx, getOrCreateSubgroupByName, name)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getOrCreateSubjectByName = `-- name: GetOrCreateSubjectByName :one
INSERT INTO subjects (name)
VALUES ($1) ON CONFLICT (name) DO
UPDATE SET name = EXCLUDED.name
    RETURNING id
`

func (q *Queries) GetOrCreateSubjectByName(ctx context.Context, name string) (int32, error) {
	row := q.db.QueryRow(ctx, getOrCreateSubjectByName, name)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getOrCreateTeacherByName = `-- name: GetOrCreateTeacherByName :one
INSERT INTO teachers (name)
VALUES ($1) ON CONFLICT (name) DO
UPDATE SET name = EXCLUDED.name
    RETURNING id
`

func (q *Queries) GetOrCreateTeacherByName(ctx context.Context, name string) (int32, error) {
	row := q.db.QueryRow(ctx, getOrCreateTeacherByName, name)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getOrCreateTimetableByName = `-- name: GetOrCreateTimetableByName :one
INSERT INTO timetables (name, date_start, date_end)
VALUES ($1, $2, $3) ON CONFLICT (name) DO
UPDATE SET name = EXCLUDED.name
    RETURNING id
`

type GetOrCreateTimetableByNameParams struct {
	Name      string
	DateStart time.Time
	DateEnd   time.Time
}

func (q *Queries) GetOrCreateTimetableByName(ctx context.Context, arg GetOrCreateTimetableByNameParams) (int32, error) {
	row := q.db.QueryRow(ctx, getOrCreateTimetableByName, arg.Name, arg.DateStart, arg.DateEnd)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getSubgroupById = `-- name: GetSubgroupById :one
SELECT id, name
FROM subgroups
WHERE id = $1
`

func (q *Queries) GetSubgroupById(ctx context.Context, id int32) (Subgroup, error) {
	row := q.db.QueryRow(ctx, getSubgroupById, id)
	var i Subgroup
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getSubgroups = `-- name: GetSubgroups :many
SELECT id, name
FROM subgroups
WHERE ($1 IS NULL OR name ILIKE '%' || $1 || '%')
ORDER BY name LIMIT $2::INTEGER
OFFSET $2::INTEGER * ($3::INTEGER)
`

type GetSubgroupsParams struct {
	Name     interface{}
	PageSize int32
	Page     int32
}

func (q *Queries) GetSubgroups(ctx context.Context, arg GetSubgroupsParams) ([]Subgroup, error) {
	rows, err := q.db.Query(ctx, getSubgroups, arg.Name, arg.PageSize, arg.Page)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subgroup
	for rows.Next() {
		var i Subgroup
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubgroupsAssignmentByLessonId = `-- name: GetSubgroupsAssignmentByLessonId :many
SELECT subgroup_id, (SELECT name FROM subgroups WHERE id = subgroup_id) AS subgroup_name
FROM subgroups_assignments WHERE lesson_id = $1
`

type GetSubgroupsAssignmentByLessonIdRow struct {
	SubgroupID   int32
	SubgroupName string
}

func (q *Queries) GetSubgroupsAssignmentByLessonId(ctx context.Context, lessonID uuid.UUID) ([]GetSubgroupsAssignmentByLessonIdRow, error) {
	rows, err := q.db.Query(ctx, getSubgroupsAssignmentByLessonId, lessonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSubgroupsAssignmentByLessonIdRow
	for rows.Next() {
		var i GetSubgroupsAssignmentByLessonIdRow
		if err := rows.Scan(&i.SubgroupID, &i.SubgroupName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubjectById = `-- name: GetSubjectById :one
SELECT id, name
FROM subjects
WHERE id = $1
`

func (q *Queries) GetSubjectById(ctx context.Context, id int32) (Subject, error) {
	row := q.db.QueryRow(ctx, getSubjectById, id)
	var i Subject
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getSubjects = `-- name: GetSubjects :many
SELECT id, name
FROM subjects
WHERE ($1 IS NULL OR name ILIKE '%' || $1 || '%')
ORDER BY name LIMIT $2::INTEGER
OFFSET $2::INTEGER * ($3::INTEGER)
`

type GetSubjectsParams struct {
	Name     interface{}
	PageSize int32
	Page     int32
}

func (q *Queries) GetSubjects(ctx context.Context, arg GetSubjectsParams) ([]Subject, error) {
	rows, err := q.db.Query(ctx, getSubjects, arg.Name, arg.PageSize, arg.Page)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subject
	for rows.Next() {
		var i Subject
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeacherById = `-- name: GetTeacherById :one
SELECT id, name
FROM teachers
WHERE id = $1
`

func (q *Queries) GetTeacherById(ctx context.Context, id int32) (Teacher, error) {
	row := q.db.QueryRow(ctx, getTeacherById, id)
	var i Teacher
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getTeacherLocationAssignmentsByLessonId = `-- name: GetTeacherLocationAssignmentsByLessonId :many
SELECT teacher_id, (SELECT name FROM teachers WHERE id = teacher_id) AS teacher_name,
       location_id, (SELECT name FROM locations WHERE id = location_id) AS location_name
FROM teacher_location_assignments WHERE lesson_id = $1
`

type GetTeacherLocationAssignmentsByLessonIdRow struct {
	TeacherID    int32
	TeacherName  string
	LocationID   int32
	LocationName string
}

func (q *Queries) GetTeacherLocationAssignmentsByLessonId(ctx context.Context, lessonID uuid.UUID) ([]GetTeacherLocationAssignmentsByLessonIdRow, error) {
	rows, err := q.db.Query(ctx, getTeacherLocationAssignmentsByLessonId, lessonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeacherLocationAssignmentsByLessonIdRow
	for rows.Next() {
		var i GetTeacherLocationAssignmentsByLessonIdRow
		if err := rows.Scan(
			&i.TeacherID,
			&i.TeacherName,
			&i.LocationID,
			&i.LocationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeachers = `-- name: GetTeachers :many
SELECT id, name
FROM teachers
WHERE ($1 IS NULL OR name ILIKE '%' || $1 || '%')
ORDER BY name LIMIT $2::INTEGER
OFFSET $2::INTEGER * ($3::INTEGER)
`

type GetTeachersParams struct {
	Name     interface{}
	PageSize int32
	Page     int32
}

func (q *Queries) GetTeachers(ctx context.Context, arg GetTeachersParams) ([]Teacher, error) {
	rows, err := q.db.Query(ctx, getTeachers, arg.Name, arg.PageSize, arg.Page)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Teacher
	for rows.Next() {
		var i Teacher
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTimetableById = `-- name: GetTimetableById :one
SELECT id, name, date_start, date_end
FROM timetables
WHERE id = $1
`

func (q *Queries) GetTimetableById(ctx context.Context, id int32) (Timetable, error) {
	row := q.db.QueryRow(ctx, getTimetableById, id)
	var i Timetable
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DateStart,
		&i.DateEnd,
	)
	return i, err
}

const getTimetables = `-- name: GetTimetables :many
SELECT id, name
FROM timetables
WHERE ($1 IS NULL OR name ILIKE '%' || $1 || '%')
ORDER BY name LIMIT $2::INTEGER
OFFSET $2::INTEGER * ($3::INTEGER)
`

type GetTimetablesParams struct {
	Name     interface{}
	PageSize int32
	Page     int32
}

type GetTimetablesRow struct {
	ID   int32
	Name string
}

func (q *Queries) GetTimetables(ctx context.Context, arg GetTimetablesParams) ([]GetTimetablesRow, error) {
	rows, err := q.db.Query(ctx, getTimetables, arg.Name, arg.PageSize, arg.Page)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTimetablesRow
	for rows.Next() {
		var i GetTimetablesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patchLessonById = `-- name: PatchLessonById :one
UPDATE lessons
SET category     = $1,
    day          = $2,
    time_start   = $3,
    time_end     = $4,
    repeat_rule  = $5,
    timetable_id = $6
WHERE id = $7 RETURNING id
`

type PatchLessonByIdParams struct {
	Category    string
	Day         int32
	TimeStart   int32
	TimeEnd     int32
	RepeatRule  int32
	TimetableID int32
	LessonID    uuid.UUID
}

func (q *Queries) PatchLessonById(ctx context.Context, arg PatchLessonByIdParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, patchLessonById,
		arg.Category,
		arg.Day,
		arg.TimeStart,
		arg.TimeEnd,
		arg.RepeatRule,
		arg.TimetableID,
		arg.LessonID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const patchLocationById = `-- name: PatchLocationById :one
UPDATE locations
SET name = $1
WHERE id = $2 RETURNING id, name
`

type PatchLocationByIdParams struct {
	Name string
	ID   int32
}

func (q *Queries) PatchLocationById(ctx context.Context, arg PatchLocationByIdParams) (Location, error) {
	row := q.db.QueryRow(ctx, patchLocationById, arg.Name, arg.ID)
	var i Location
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const patchSubgroupById = `-- name: PatchSubgroupById :one
UPDATE subgroups
SET name = $1
WHERE id = $2 RETURNING id, name
`

type PatchSubgroupByIdParams struct {
	Name string
	ID   int32
}

func (q *Queries) PatchSubgroupById(ctx context.Context, arg PatchSubgroupByIdParams) (Subgroup, error) {
	row := q.db.QueryRow(ctx, patchSubgroupById, arg.Name, arg.ID)
	var i Subgroup
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const patchSubjectById = `-- name: PatchSubjectById :one
UPDATE subjects
SET name = $1
WHERE id = $2 RETURNING id, name
`

type PatchSubjectByIdParams struct {
	Name string
	ID   int32
}

func (q *Queries) PatchSubjectById(ctx context.Context, arg PatchSubjectByIdParams) (Subject, error) {
	row := q.db.QueryRow(ctx, patchSubjectById, arg.Name, arg.ID)
	var i Subject
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const patchTeacherById = `-- name: PatchTeacherById :one
UPDATE teachers
SET name = $1
WHERE id = $2 RETURNING id, name
`

type PatchTeacherByIdParams struct {
	Name string
	ID   int32
}

func (q *Queries) PatchTeacherById(ctx context.Context, arg PatchTeacherByIdParams) (Teacher, error) {
	row := q.db.QueryRow(ctx, patchTeacherById, arg.Name, arg.ID)
	var i Teacher
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const patchTimetableById = `-- name: PatchTimetableById :one
UPDATE timetables
SET name       = $1,
    date_start = $2,
    date_end   = $3
WHERE id = $4 RETURNING id, name, date_start, date_end
`

type PatchTimetableByIdParams struct {
	Name      string
	DateStart time.Time
	DateEnd   time.Time
	ID        int32
}

func (q *Queries) PatchTimetableById(ctx context.Context, arg PatchTimetableByIdParams) (Timetable, error) {
	row := q.db.QueryRow(ctx, patchTimetableById,
		arg.Name,
		arg.DateStart,
		arg.DateEnd,
		arg.ID,
	)
	var i Timetable
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DateStart,
		&i.DateEnd,
	)
	return i, err
}
