/**
 * pstu-timetable
 * pstu-timetable
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIListSubgroups.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIListSubgroups::OAIListSubgroups(const QString &json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIListSubgroups::OAIListSubgroups() {
    this->initializeModel();
}

OAIListSubgroups::~OAIListSubgroups() {}

void OAIListSubgroups::initializeModel() {

    m_pagination_isSet = false;
    m_pagination_isValid = false;

    m_subgroups_isSet = false;
    m_subgroups_isValid = false;
}

void OAIListSubgroups::fromJson(const QString &jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIListSubgroups::fromJsonObject(QJsonObject json) {

    m_pagination_isValid = ::OpenAPI::fromJsonValue(m_pagination, json[QString("pagination")]);
    m_pagination_isSet = !json[QString("pagination")].isNull() && m_pagination_isValid;

    m_subgroups_isValid = ::OpenAPI::fromJsonValue(m_subgroups, json[QString("subgroups")]);
    m_subgroups_isSet = !json[QString("subgroups")].isNull() && m_subgroups_isValid;
}

QString OAIListSubgroups::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIListSubgroups::asJsonObject() const {
    QJsonObject obj;
    if (m_pagination.isSet()) {
        obj.insert(QString("pagination"), ::OpenAPI::toJsonValue(m_pagination));
    }
    if (m_subgroups.size() > 0) {
        obj.insert(QString("subgroups"), ::OpenAPI::toJsonValue(m_subgroups));
    }
    return obj;
}

OAIPagination OAIListSubgroups::getPagination() const {
    return m_pagination;
}
void OAIListSubgroups::setPagination(const OAIPagination &pagination) {
    m_pagination = pagination;
    m_pagination_isSet = true;
}

bool OAIListSubgroups::is_pagination_Set() const{
    return m_pagination_isSet;
}

bool OAIListSubgroups::is_pagination_Valid() const{
    return m_pagination_isValid;
}

QList<OAISubgroup> OAIListSubgroups::getSubgroups() const {
    return m_subgroups;
}
void OAIListSubgroups::setSubgroups(const QList<OAISubgroup> &subgroups) {
    m_subgroups = subgroups;
    m_subgroups_isSet = true;
}

bool OAIListSubgroups::is_subgroups_Set() const{
    return m_subgroups_isSet;
}

bool OAIListSubgroups::is_subgroups_Valid() const{
    return m_subgroups_isValid;
}

bool OAIListSubgroups::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_pagination.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_subgroups.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIListSubgroups::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_pagination_isValid && m_subgroups_isValid && true;
}

} // namespace OpenAPI
