/**
 * pstu-timetable
 * pstu-timetable
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIListTeachers.h
 *
 * 
 */

#ifndef OAIListTeachers_H
#define OAIListTeachers_H

#include <QJsonObject>

#include "OAIPagination.h"
#include "OAITeacher.h"
#include <QList>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAIPagination;
class OAITeacher;

class OAIListTeachers : public OAIObject {
public:
    OAIListTeachers();
    OAIListTeachers(const QString &json);
    ~OAIListTeachers() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(const QString &jsonString) override;

    OAIPagination getPagination() const;
    void setPagination(const OAIPagination &pagination);
    bool is_pagination_Set() const;
    bool is_pagination_Valid() const;

    QList<OAITeacher> getTeachers() const;
    void setTeachers(const QList<OAITeacher> &teachers);
    bool is_teachers_Set() const;
    bool is_teachers_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    OAIPagination m_pagination;
    bool m_pagination_isSet;
    bool m_pagination_isValid;

    QList<OAITeacher> m_teachers;
    bool m_teachers_isSet;
    bool m_teachers_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIListTeachers)

#endif // OAIListTeachers_H
