/**
 * pstu-timetable
 * pstu-timetable
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAILesson.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAILesson::OAILesson(const QString &json) {
    this->initializeModel();
    this->fromJson(json);
}

OAILesson::OAILesson() {
    this->initializeModel();
}

OAILesson::~OAILesson() {}

void OAILesson::initializeModel() {

    m_id_isSet = false;
    m_id_isValid = false;

    m_subject_isSet = false;
    m_subject_isValid = false;

    m_category_isSet = false;
    m_category_isValid = false;

    m_day_isSet = false;
    m_day_isValid = false;

    m_time_start_isSet = false;
    m_time_start_isValid = false;

    m_time_end_isSet = false;
    m_time_end_isValid = false;

    m_repeat_rule_isSet = false;
    m_repeat_rule_isValid = false;

    m_timetable_isSet = false;
    m_timetable_isValid = false;

    m_teacher_location_assignments_isSet = false;
    m_teacher_location_assignments_isValid = false;

    m_subgroups_isSet = false;
    m_subgroups_isValid = false;
}

void OAILesson::fromJson(const QString &jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAILesson::fromJsonObject(QJsonObject json) {

    m_id_isValid = ::OpenAPI::fromJsonValue(m_id, json[QString("id")]);
    m_id_isSet = !json[QString("id")].isNull() && m_id_isValid;

    m_subject_isValid = ::OpenAPI::fromJsonValue(m_subject, json[QString("subject")]);
    m_subject_isSet = !json[QString("subject")].isNull() && m_subject_isValid;

    m_category_isValid = ::OpenAPI::fromJsonValue(m_category, json[QString("category")]);
    m_category_isSet = !json[QString("category")].isNull() && m_category_isValid;

    m_day_isValid = ::OpenAPI::fromJsonValue(m_day, json[QString("day")]);
    m_day_isSet = !json[QString("day")].isNull() && m_day_isValid;

    m_time_start_isValid = ::OpenAPI::fromJsonValue(m_time_start, json[QString("time_start")]);
    m_time_start_isSet = !json[QString("time_start")].isNull() && m_time_start_isValid;

    m_time_end_isValid = ::OpenAPI::fromJsonValue(m_time_end, json[QString("time_end")]);
    m_time_end_isSet = !json[QString("time_end")].isNull() && m_time_end_isValid;

    m_repeat_rule_isValid = ::OpenAPI::fromJsonValue(m_repeat_rule, json[QString("repeat_rule")]);
    m_repeat_rule_isSet = !json[QString("repeat_rule")].isNull() && m_repeat_rule_isValid;

    m_timetable_isValid = ::OpenAPI::fromJsonValue(m_timetable, json[QString("timetable")]);
    m_timetable_isSet = !json[QString("timetable")].isNull() && m_timetable_isValid;

    m_teacher_location_assignments_isValid = ::OpenAPI::fromJsonValue(m_teacher_location_assignments, json[QString("teacher_location_assignments")]);
    m_teacher_location_assignments_isSet = !json[QString("teacher_location_assignments")].isNull() && m_teacher_location_assignments_isValid;

    m_subgroups_isValid = ::OpenAPI::fromJsonValue(m_subgroups, json[QString("subgroups")]);
    m_subgroups_isSet = !json[QString("subgroups")].isNull() && m_subgroups_isValid;
}

QString OAILesson::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAILesson::asJsonObject() const {
    QJsonObject obj;
    if (m_id_isSet) {
        obj.insert(QString("id"), ::OpenAPI::toJsonValue(m_id));
    }
    if (m_subject.isSet()) {
        obj.insert(QString("subject"), ::OpenAPI::toJsonValue(m_subject));
    }
    if (m_category_isSet) {
        obj.insert(QString("category"), ::OpenAPI::toJsonValue(m_category));
    }
    if (m_day_isSet) {
        obj.insert(QString("day"), ::OpenAPI::toJsonValue(m_day));
    }
    if (m_time_start_isSet) {
        obj.insert(QString("time_start"), ::OpenAPI::toJsonValue(m_time_start));
    }
    if (m_time_end_isSet) {
        obj.insert(QString("time_end"), ::OpenAPI::toJsonValue(m_time_end));
    }
    if (m_repeat_rule_isSet) {
        obj.insert(QString("repeat_rule"), ::OpenAPI::toJsonValue(m_repeat_rule));
    }
    if (m_timetable.isSet()) {
        obj.insert(QString("timetable"), ::OpenAPI::toJsonValue(m_timetable));
    }
    if (m_teacher_location_assignments.size() > 0) {
        obj.insert(QString("teacher_location_assignments"), ::OpenAPI::toJsonValue(m_teacher_location_assignments));
    }
    if (m_subgroups.size() > 0) {
        obj.insert(QString("subgroups"), ::OpenAPI::toJsonValue(m_subgroups));
    }
    return obj;
}

QString OAILesson::getId() const {
    return m_id;
}
void OAILesson::setId(const QString &id) {
    m_id = id;
    m_id_isSet = true;
}

bool OAILesson::is_id_Set() const{
    return m_id_isSet;
}

bool OAILesson::is_id_Valid() const{
    return m_id_isValid;
}

OAISubject OAILesson::getSubject() const {
    return m_subject;
}
void OAILesson::setSubject(const OAISubject &subject) {
    m_subject = subject;
    m_subject_isSet = true;
}

bool OAILesson::is_subject_Set() const{
    return m_subject_isSet;
}

bool OAILesson::is_subject_Valid() const{
    return m_subject_isValid;
}

QString OAILesson::getCategory() const {
    return m_category;
}
void OAILesson::setCategory(const QString &category) {
    m_category = category;
    m_category_isSet = true;
}

bool OAILesson::is_category_Set() const{
    return m_category_isSet;
}

bool OAILesson::is_category_Valid() const{
    return m_category_isValid;
}

qint32 OAILesson::getDay() const {
    return m_day;
}
void OAILesson::setDay(const qint32 &day) {
    m_day = day;
    m_day_isSet = true;
}

bool OAILesson::is_day_Set() const{
    return m_day_isSet;
}

bool OAILesson::is_day_Valid() const{
    return m_day_isValid;
}

qint32 OAILesson::getTimeStart() const {
    return m_time_start;
}
void OAILesson::setTimeStart(const qint32 &time_start) {
    m_time_start = time_start;
    m_time_start_isSet = true;
}

bool OAILesson::is_time_start_Set() const{
    return m_time_start_isSet;
}

bool OAILesson::is_time_start_Valid() const{
    return m_time_start_isValid;
}

qint32 OAILesson::getTimeEnd() const {
    return m_time_end;
}
void OAILesson::setTimeEnd(const qint32 &time_end) {
    m_time_end = time_end;
    m_time_end_isSet = true;
}

bool OAILesson::is_time_end_Set() const{
    return m_time_end_isSet;
}

bool OAILesson::is_time_end_Valid() const{
    return m_time_end_isValid;
}

qint32 OAILesson::getRepeatRule() const {
    return m_repeat_rule;
}
void OAILesson::setRepeatRule(const qint32 &repeat_rule) {
    m_repeat_rule = repeat_rule;
    m_repeat_rule_isSet = true;
}

bool OAILesson::is_repeat_rule_Set() const{
    return m_repeat_rule_isSet;
}

bool OAILesson::is_repeat_rule_Valid() const{
    return m_repeat_rule_isValid;
}

OAITimetable OAILesson::getTimetable() const {
    return m_timetable;
}
void OAILesson::setTimetable(const OAITimetable &timetable) {
    m_timetable = timetable;
    m_timetable_isSet = true;
}

bool OAILesson::is_timetable_Set() const{
    return m_timetable_isSet;
}

bool OAILesson::is_timetable_Valid() const{
    return m_timetable_isValid;
}

QList<OAITeacherLocationAssignment> OAILesson::getTeacherLocationAssignments() const {
    return m_teacher_location_assignments;
}
void OAILesson::setTeacherLocationAssignments(const QList<OAITeacherLocationAssignment> &teacher_location_assignments) {
    m_teacher_location_assignments = teacher_location_assignments;
    m_teacher_location_assignments_isSet = true;
}

bool OAILesson::is_teacher_location_assignments_Set() const{
    return m_teacher_location_assignments_isSet;
}

bool OAILesson::is_teacher_location_assignments_Valid() const{
    return m_teacher_location_assignments_isValid;
}

QList<OAISubgroup> OAILesson::getSubgroups() const {
    return m_subgroups;
}
void OAILesson::setSubgroups(const QList<OAISubgroup> &subgroups) {
    m_subgroups = subgroups;
    m_subgroups_isSet = true;
}

bool OAILesson::is_subgroups_Set() const{
    return m_subgroups_isSet;
}

bool OAILesson::is_subgroups_Valid() const{
    return m_subgroups_isValid;
}

bool OAILesson::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_subject.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_category_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_day_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_time_start_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_time_end_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_repeat_rule_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_timetable.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_teacher_location_assignments.size() > 0) {
            isObjectUpdated = true;
            break;
        }

        if (m_subgroups.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAILesson::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_id_isValid && m_subject_isValid && m_category_isValid && m_day_isValid && m_time_start_isValid && m_time_end_isValid && m_repeat_rule_isValid && m_timetable_isValid && m_teacher_location_assignments_isValid && m_subgroups_isValid && true;
}

} // namespace OpenAPI
