/**
 * pstu-timetable
 * pstu-timetable
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIListSubjects.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIListSubjects::OAIListSubjects(const QString &json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIListSubjects::OAIListSubjects() {
    this->initializeModel();
}

OAIListSubjects::~OAIListSubjects() {}

void OAIListSubjects::initializeModel() {

    m_pagination_isSet = false;
    m_pagination_isValid = false;

    m_subjects_isSet = false;
    m_subjects_isValid = false;
}

void OAIListSubjects::fromJson(const QString &jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIListSubjects::fromJsonObject(QJsonObject json) {

    m_pagination_isValid = ::OpenAPI::fromJsonValue(m_pagination, json[QString("pagination")]);
    m_pagination_isSet = !json[QString("pagination")].isNull() && m_pagination_isValid;

    m_subjects_isValid = ::OpenAPI::fromJsonValue(m_subjects, json[QString("subjects")]);
    m_subjects_isSet = !json[QString("subjects")].isNull() && m_subjects_isValid;
}

QString OAIListSubjects::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIListSubjects::asJsonObject() const {
    QJsonObject obj;
    if (m_pagination.isSet()) {
        obj.insert(QString("pagination"), ::OpenAPI::toJsonValue(m_pagination));
    }
    if (m_subjects.size() > 0) {
        obj.insert(QString("subjects"), ::OpenAPI::toJsonValue(m_subjects));
    }
    return obj;
}

OAIPagination OAIListSubjects::getPagination() const {
    return m_pagination;
}
void OAIListSubjects::setPagination(const OAIPagination &pagination) {
    m_pagination = pagination;
    m_pagination_isSet = true;
}

bool OAIListSubjects::is_pagination_Set() const{
    return m_pagination_isSet;
}

bool OAIListSubjects::is_pagination_Valid() const{
    return m_pagination_isValid;
}

QList<OAISubject> OAIListSubjects::getSubjects() const {
    return m_subjects;
}
void OAIListSubjects::setSubjects(const QList<OAISubject> &subjects) {
    m_subjects = subjects;
    m_subjects_isSet = true;
}

bool OAIListSubjects::is_subjects_Set() const{
    return m_subjects_isSet;
}

bool OAIListSubjects::is_subjects_Valid() const{
    return m_subjects_isValid;
}

bool OAIListSubjects::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_pagination.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_subjects.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIListSubjects::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_pagination_isValid && m_subjects_isValid && true;
}

} // namespace OpenAPI
