/**
 * pstu-timetable
 * pstu-timetable
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIPagination.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIPagination::OAIPagination(const QString &json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIPagination::OAIPagination() {
    this->initializeModel();
}

OAIPagination::~OAIPagination() {}

void OAIPagination::initializeModel() {

    m_total_pages_isSet = false;
    m_total_pages_isValid = false;

    m_page_isSet = false;
    m_page_isValid = false;
}

void OAIPagination::fromJson(const QString &jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIPagination::fromJsonObject(QJsonObject json) {

    m_total_pages_isValid = ::OpenAPI::fromJsonValue(m_total_pages, json[QString("total_pages")]);
    m_total_pages_isSet = !json[QString("total_pages")].isNull() && m_total_pages_isValid;

    m_page_isValid = ::OpenAPI::fromJsonValue(m_page, json[QString("page")]);
    m_page_isSet = !json[QString("page")].isNull() && m_page_isValid;
}

QString OAIPagination::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIPagination::asJsonObject() const {
    QJsonObject obj;
    if (m_total_pages_isSet) {
        obj.insert(QString("total_pages"), ::OpenAPI::toJsonValue(m_total_pages));
    }
    if (m_page_isSet) {
        obj.insert(QString("page"), ::OpenAPI::toJsonValue(m_page));
    }
    return obj;
}

qint32 OAIPagination::getTotalPages() const {
    return m_total_pages;
}
void OAIPagination::setTotalPages(const qint32 &total_pages) {
    m_total_pages = total_pages;
    m_total_pages_isSet = true;
}

bool OAIPagination::is_total_pages_Set() const{
    return m_total_pages_isSet;
}

bool OAIPagination::is_total_pages_Valid() const{
    return m_total_pages_isValid;
}

qint32 OAIPagination::getPage() const {
    return m_page;
}
void OAIPagination::setPage(const qint32 &page) {
    m_page = page;
    m_page_isSet = true;
}

bool OAIPagination::is_page_Set() const{
    return m_page_isSet;
}

bool OAIPagination::is_page_Valid() const{
    return m_page_isValid;
}

bool OAIPagination::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_total_pages_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_page_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIPagination::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_total_pages_isValid && m_page_isValid && true;
}

} // namespace OpenAPI
