/**
 * pstu-timetable
 * pstu-timetable
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAITeacherLocationAssignment.h
 *
 * 
 */

#ifndef OAITeacherLocationAssignment_H
#define OAITeacherLocationAssignment_H

#include <QJsonObject>

#include "OAILocation.h"
#include "OAITeacher.h"

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAITeacher;
class OAILocation;

class OAITeacherLocationAssignment : public OAIObject {
public:
    OAITeacherLocationAssignment();
    OAITeacherLocationAssignment(const QString &json);
    ~OAITeacherLocationAssignment() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(const QString &jsonString) override;

    OAITeacher getTeacher() const;
    void setTeacher(const OAITeacher &teacher);
    bool is_teacher_Set() const;
    bool is_teacher_Valid() const;

    OAILocation getLocation() const;
    void setLocation(const OAILocation &location);
    bool is_location_Set() const;
    bool is_location_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    OAITeacher m_teacher;
    bool m_teacher_isSet;
    bool m_teacher_isValid;

    OAILocation m_location;
    bool m_location_isSet;
    bool m_location_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAITeacherLocationAssignment)

#endif // OAITeacherLocationAssignment_H
