/**
 * pstu-timetable
 * pstu-timetable
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAITimetable.h
 *
 * 
 */

#ifndef OAITimetable_H
#define OAITimetable_H

#include <QJsonObject>

#include <QDateTime>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAITimetable : public OAIObject {
public:
    OAITimetable();
    OAITimetable(const QString &json);
    ~OAITimetable() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(const QString &jsonString) override;

    qint32 getId() const;
    void setId(const qint32 &id);
    bool is_id_Set() const;
    bool is_id_Valid() const;

    QString getName() const;
    void setName(const QString &name);
    bool is_name_Set() const;
    bool is_name_Valid() const;

    QDateTime getDateStart() const;
    void setDateStart(const QDateTime &date_start);
    bool is_date_start_Set() const;
    bool is_date_start_Valid() const;

    QDateTime getDateEnd() const;
    void setDateEnd(const QDateTime &date_end);
    bool is_date_end_Set() const;
    bool is_date_end_Valid() const;

    qint32 getWeek() const;
    void setWeek(const qint32 &week);
    bool is_week_Set() const;
    bool is_week_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    qint32 m_id;
    bool m_id_isSet;
    bool m_id_isValid;

    QString m_name;
    bool m_name_isSet;
    bool m_name_isValid;

    QDateTime m_date_start;
    bool m_date_start_isSet;
    bool m_date_start_isValid;

    QDateTime m_date_end;
    bool m_date_end_isSet;
    bool m_date_end_isValid;

    qint32 m_week;
    bool m_week_isSet;
    bool m_week_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAITimetable)

#endif // OAITimetable_H
