/**
 * pstu-timetable
 * pstu-timetable
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef OAI_OAIDefaultApi_H
#define OAI_OAIDefaultApi_H

#include "OAIHelpers.h"
#include "OAIHttpRequest.h"
#include "OAIServerConfiguration.h"
#include "OAIOauth.h"

#include "OAIError.h"
#include "OAIHttpFileElement.h"
#include "OAILesson.h"
#include "OAIListErrors.h"
#include "OAIListLocations.h"
#include "OAIListSubgroups.h"
#include "OAIListSubjects.h"
#include "OAIListTeachers.h"
#include "OAIListTimetables.h"
#include "OAILocation.h"
#include "OAISubgroup.h"
#include "OAISubject.h"
#include "OAITeacher.h"
#include "OAITimetable.h"
#include <QString>

#include <QObject>
#include <QByteArray>
#include <QStringList>
#include <QList>
#include <QNetworkAccessManager>

namespace OpenAPI {

class OAIDefaultApi : public QObject {
    Q_OBJECT

public:
    OAIDefaultApi(const int timeOut = 0);
    ~OAIDefaultApi();

    void initializeServerConfigs();
    int setDefaultServerValue(int serverIndex,const QString &operation, const QString &variable,const QString &val);
    void setServerIndex(const QString &operation, int serverIndex);
    void setServerIndex(int serverIndex);
    void setApiKey(const QString &apiKeyName, const QString &apiKey);
    void setBearerToken(const QString &token);
    void setUsername(const QString &username);
    void setPassword(const QString &password);
    void setTimeOut(const int timeOut);
    void setWorkingDirectory(const QString &path);
    void setNetworkAccessManager(QNetworkAccessManager* manager);
    int addServerConfiguration(const QString &operation, const QUrl &url, const QString &description = "", const QMap<QString, OAIServerVariable> &variables = QMap<QString, OAIServerVariable>());
    void setNewServerForAllOperations(const QUrl &url, const QString &description = "", const QMap<QString, OAIServerVariable> &variables =  QMap<QString, OAIServerVariable>());
    void setNewServer(const QString &operation, const QUrl &url, const QString &description = "", const QMap<QString, OAIServerVariable> &variables =  QMap<QString, OAIServerVariable>());
    void addHeaders(const QString &key, const QString &value);
    void enableRequestCompression();
    void enableResponseCompression();
    void abortRequests();
    QString getParamStylePrefix(const QString &style);
    QString getParamStyleSuffix(const QString &style);
    QString getParamStyleDelimiter(const QString &style, const QString &name, bool isExplode);

    /**
    * @param[in]  page_size qint32 [optional]
    * @param[in]  page qint32 [optional]
    */
    virtual void errorsGet(const ::OpenAPI::OptionalParam<qint32> &page_size = ::OpenAPI::OptionalParam<qint32>(), const ::OpenAPI::OptionalParam<qint32> &page = ::OpenAPI::OptionalParam<qint32>());

    /**
    * @param[in]  id qint32 [required]
    */
    virtual void errorsIdGet(const qint32 &id);

    /**
    * @param[in]  file OAIHttpFileElement [required]
    */
    virtual void importPost(const OAIHttpFileElement &file);

    /**
    * @param[in]  id QString [required]
    */
    virtual void lessonsIdDelete(const QString &id);

    /**
    * @param[in]  id QString [required]
    */
    virtual void lessonsIdGet(const QString &id);

    /**
    * @param[in]  id QString [required]
    * @param[in]  oai_lesson OAILesson [required]
    */
    virtual void lessonsIdPatch(const QString &id, const OAILesson &oai_lesson);

    /**
    * @param[in]  oai_lesson OAILesson [required]
    */
    virtual void lessonsPost(const OAILesson &oai_lesson);

    /**
    * @param[in]  id qint32 [required]
    * @param[in]  table QString [required]
    * @param[in]  format QString [optional]
    */
    virtual void lessonsTableIdGet(const qint32 &id, const QString &table, const ::OpenAPI::OptionalParam<QString> &format = ::OpenAPI::OptionalParam<QString>());

    /**
    * @param[in]  page_size qint32 [optional]
    * @param[in]  page qint32 [optional]
    * @param[in]  search QString [optional]
    */
    virtual void locationsGet(const ::OpenAPI::OptionalParam<qint32> &page_size = ::OpenAPI::OptionalParam<qint32>(), const ::OpenAPI::OptionalParam<qint32> &page = ::OpenAPI::OptionalParam<qint32>(), const ::OpenAPI::OptionalParam<QString> &search = ::OpenAPI::OptionalParam<QString>());

    /**
    * @param[in]  id qint32 [required]
    */
    virtual void locationsIdDelete(const qint32 &id);

    /**
    * @param[in]  id qint32 [required]
    */
    virtual void locationsIdGet(const qint32 &id);

    /**
    * @param[in]  id qint32 [required]
    * @param[in]  oai_location OAILocation [required]
    */
    virtual void locationsIdPatch(const qint32 &id, const OAILocation &oai_location);

    /**
    * @param[in]  oai_location OAILocation [required]
    */
    virtual void locationsPost(const OAILocation &oai_location);

    /**
    * @param[in]  page_size qint32 [optional]
    * @param[in]  page qint32 [optional]
    * @param[in]  search QString [optional]
    */
    virtual void subgroupsGet(const ::OpenAPI::OptionalParam<qint32> &page_size = ::OpenAPI::OptionalParam<qint32>(), const ::OpenAPI::OptionalParam<qint32> &page = ::OpenAPI::OptionalParam<qint32>(), const ::OpenAPI::OptionalParam<QString> &search = ::OpenAPI::OptionalParam<QString>());

    /**
    * @param[in]  id qint32 [required]
    */
    virtual void subgroupsIdDelete(const qint32 &id);

    /**
    * @param[in]  id qint32 [required]
    */
    virtual void subgroupsIdGet(const qint32 &id);

    /**
    * @param[in]  id qint32 [required]
    * @param[in]  oai_subgroup OAISubgroup [required]
    */
    virtual void subgroupsIdPatch(const qint32 &id, const OAISubgroup &oai_subgroup);

    /**
    * @param[in]  oai_subgroup OAISubgroup [required]
    */
    virtual void subgroupsPost(const OAISubgroup &oai_subgroup);

    /**
    * @param[in]  page_size qint32 [optional]
    * @param[in]  page qint32 [optional]
    * @param[in]  search QString [optional]
    */
    virtual void subjectsGet(const ::OpenAPI::OptionalParam<qint32> &page_size = ::OpenAPI::OptionalParam<qint32>(), const ::OpenAPI::OptionalParam<qint32> &page = ::OpenAPI::OptionalParam<qint32>(), const ::OpenAPI::OptionalParam<QString> &search = ::OpenAPI::OptionalParam<QString>());

    /**
    * @param[in]  id qint32 [required]
    */
    virtual void subjectsIdDelete(const qint32 &id);

    /**
    * @param[in]  id qint32 [required]
    */
    virtual void subjectsIdGet(const qint32 &id);

    /**
    * @param[in]  id qint32 [required]
    * @param[in]  oai_subject OAISubject [required]
    */
    virtual void subjectsIdPatch(const qint32 &id, const OAISubject &oai_subject);

    /**
    * @param[in]  oai_subject OAISubject [required]
    */
    virtual void subjectsPost(const OAISubject &oai_subject);

    /**
    * @param[in]  page_size qint32 [optional]
    * @param[in]  page qint32 [optional]
    * @param[in]  search QString [optional]
    */
    virtual void teachersGet(const ::OpenAPI::OptionalParam<qint32> &page_size = ::OpenAPI::OptionalParam<qint32>(), const ::OpenAPI::OptionalParam<qint32> &page = ::OpenAPI::OptionalParam<qint32>(), const ::OpenAPI::OptionalParam<QString> &search = ::OpenAPI::OptionalParam<QString>());

    /**
    * @param[in]  id qint32 [required]
    */
    virtual void teachersIdDelete(const qint32 &id);

    /**
    * @param[in]  id qint32 [required]
    */
    virtual void teachersIdGet(const qint32 &id);

    /**
    * @param[in]  id qint32 [required]
    * @param[in]  oai_teacher OAITeacher [required]
    */
    virtual void teachersIdPatch(const qint32 &id, const OAITeacher &oai_teacher);

    /**
    * @param[in]  oai_teacher OAITeacher [required]
    */
    virtual void teachersPost(const OAITeacher &oai_teacher);

    /**
    * @param[in]  page_size qint32 [optional]
    * @param[in]  page qint32 [optional]
    * @param[in]  search QString [optional]
    */
    virtual void timetablesGet(const ::OpenAPI::OptionalParam<qint32> &page_size = ::OpenAPI::OptionalParam<qint32>(), const ::OpenAPI::OptionalParam<qint32> &page = ::OpenAPI::OptionalParam<qint32>(), const ::OpenAPI::OptionalParam<QString> &search = ::OpenAPI::OptionalParam<QString>());

    /**
    * @param[in]  id qint32 [required]
    */
    virtual void timetablesIdDelete(const qint32 &id);

    /**
    * @param[in]  id qint32 [required]
    */
    virtual void timetablesIdGet(const qint32 &id);

    /**
    * @param[in]  id qint32 [required]
    * @param[in]  oai_timetable OAITimetable [required]
    */
    virtual void timetablesIdPatch(const qint32 &id, const OAITimetable &oai_timetable);

    /**
    * @param[in]  oai_timetable OAITimetable [required]
    */
    virtual void timetablesPost(const OAITimetable &oai_timetable);


private:
    enum class OauthMethod : int {
        INVALID_VALUE_OPENAPI_GENERATED = 0,
        ImplicitFlow = 1,
        AuthorizationFlow = 2,
        ClientCredentialsFlow = 3,
        ResourceOwnerPasswordFlow = 4
    };
    QMap<QString,int> _serverIndices;
    QMap<QString,QList<OAIServerConfiguration>> _serverConfigs;
    QMap<QString, QString> _apiKeys;
    QString _bearerToken;
    QString _username;
    QString _password;
    int _timeOut;
    QString _workingDirectory;
    QNetworkAccessManager* _manager;
    QMap<QString, QString> _defaultHeaders;
    bool _isResponseCompressionEnabled;
    bool _isRequestCompressionEnabled;
    OAIHttpRequestInput _latestInput;
    OAIHttpRequestWorker *_latestWorker;
    QStringList _latestScope;
    OauthCode _authFlow;
    OauthImplicit _implicitFlow;
    OauthCredentials _credentialFlow;
    OauthPassword _passwordFlow;
    OauthMethod _OauthMethod = OauthMethod::INVALID_VALUE_OPENAPI_GENERATED;

    void errorsGetCallback(OAIHttpRequestWorker *worker);
    void errorsIdGetCallback(OAIHttpRequestWorker *worker);
    void importPostCallback(OAIHttpRequestWorker *worker);
    void lessonsIdDeleteCallback(OAIHttpRequestWorker *worker);
    void lessonsIdGetCallback(OAIHttpRequestWorker *worker);
    void lessonsIdPatchCallback(OAIHttpRequestWorker *worker);
    void lessonsPostCallback(OAIHttpRequestWorker *worker);
    void lessonsTableIdGetCallback(OAIHttpRequestWorker *worker);
    void locationsGetCallback(OAIHttpRequestWorker *worker);
    void locationsIdDeleteCallback(OAIHttpRequestWorker *worker);
    void locationsIdGetCallback(OAIHttpRequestWorker *worker);
    void locationsIdPatchCallback(OAIHttpRequestWorker *worker);
    void locationsPostCallback(OAIHttpRequestWorker *worker);
    void subgroupsGetCallback(OAIHttpRequestWorker *worker);
    void subgroupsIdDeleteCallback(OAIHttpRequestWorker *worker);
    void subgroupsIdGetCallback(OAIHttpRequestWorker *worker);
    void subgroupsIdPatchCallback(OAIHttpRequestWorker *worker);
    void subgroupsPostCallback(OAIHttpRequestWorker *worker);
    void subjectsGetCallback(OAIHttpRequestWorker *worker);
    void subjectsIdDeleteCallback(OAIHttpRequestWorker *worker);
    void subjectsIdGetCallback(OAIHttpRequestWorker *worker);
    void subjectsIdPatchCallback(OAIHttpRequestWorker *worker);
    void subjectsPostCallback(OAIHttpRequestWorker *worker);
    void teachersGetCallback(OAIHttpRequestWorker *worker);
    void teachersIdDeleteCallback(OAIHttpRequestWorker *worker);
    void teachersIdGetCallback(OAIHttpRequestWorker *worker);
    void teachersIdPatchCallback(OAIHttpRequestWorker *worker);
    void teachersPostCallback(OAIHttpRequestWorker *worker);
    void timetablesGetCallback(OAIHttpRequestWorker *worker);
    void timetablesIdDeleteCallback(OAIHttpRequestWorker *worker);
    void timetablesIdGetCallback(OAIHttpRequestWorker *worker);
    void timetablesIdPatchCallback(OAIHttpRequestWorker *worker);
    void timetablesPostCallback(OAIHttpRequestWorker *worker);

Q_SIGNALS:

    void errorsGetSignal(OAIListErrors summary);
    void errorsIdGetSignal(OAIError summary);
    void importPostSignal(OAIListErrors summary);
    void lessonsIdDeleteSignal();
    void lessonsIdGetSignal(OAILesson summary);
    void lessonsIdPatchSignal(OAILesson summary);
    void lessonsPostSignal(OAILesson summary);
    void lessonsTableIdGetSignal(QList<OAILesson> summary);
    void locationsGetSignal(OAIListLocations summary);
    void locationsIdDeleteSignal();
    void locationsIdGetSignal(OAILocation summary);
    void locationsIdPatchSignal(OAILocation summary);
    void locationsPostSignal(OAILocation summary);
    void subgroupsGetSignal(OAIListSubgroups summary);
    void subgroupsIdDeleteSignal();
    void subgroupsIdGetSignal(OAISubgroup summary);
    void subgroupsIdPatchSignal(OAISubgroup summary);
    void subgroupsPostSignal(OAISubgroup summary);
    void subjectsGetSignal(OAIListSubjects summary);
    void subjectsIdDeleteSignal();
    void subjectsIdGetSignal(OAISubject summary);
    void subjectsIdPatchSignal(OAISubject summary);
    void subjectsPostSignal(OAISubject summary);
    void teachersGetSignal(OAIListTeachers summary);
    void teachersIdDeleteSignal();
    void teachersIdGetSignal(OAITeacher summary);
    void teachersIdPatchSignal(OAITeacher summary);
    void teachersPostSignal(OAITeacher summary);
    void timetablesGetSignal(OAIListTimetables summary);
    void timetablesIdDeleteSignal();
    void timetablesIdGetSignal(OAITimetable summary);
    void timetablesIdPatchSignal(OAITimetable summary);
    void timetablesPostSignal(OAITimetable summary);


    void errorsGetSignalFull(OAIHttpRequestWorker *worker, OAIListErrors summary);
    void errorsIdGetSignalFull(OAIHttpRequestWorker *worker, OAIError summary);
    void importPostSignalFull(OAIHttpRequestWorker *worker, OAIListErrors summary);
    void lessonsIdDeleteSignalFull(OAIHttpRequestWorker *worker);
    void lessonsIdGetSignalFull(OAIHttpRequestWorker *worker, OAILesson summary);
    void lessonsIdPatchSignalFull(OAIHttpRequestWorker *worker, OAILesson summary);
    void lessonsPostSignalFull(OAIHttpRequestWorker *worker, OAILesson summary);
    void lessonsTableIdGetSignalFull(OAIHttpRequestWorker *worker, QList<OAILesson> summary);
    void locationsGetSignalFull(OAIHttpRequestWorker *worker, OAIListLocations summary);
    void locationsIdDeleteSignalFull(OAIHttpRequestWorker *worker);
    void locationsIdGetSignalFull(OAIHttpRequestWorker *worker, OAILocation summary);
    void locationsIdPatchSignalFull(OAIHttpRequestWorker *worker, OAILocation summary);
    void locationsPostSignalFull(OAIHttpRequestWorker *worker, OAILocation summary);
    void subgroupsGetSignalFull(OAIHttpRequestWorker *worker, OAIListSubgroups summary);
    void subgroupsIdDeleteSignalFull(OAIHttpRequestWorker *worker);
    void subgroupsIdGetSignalFull(OAIHttpRequestWorker *worker, OAISubgroup summary);
    void subgroupsIdPatchSignalFull(OAIHttpRequestWorker *worker, OAISubgroup summary);
    void subgroupsPostSignalFull(OAIHttpRequestWorker *worker, OAISubgroup summary);
    void subjectsGetSignalFull(OAIHttpRequestWorker *worker, OAIListSubjects summary);
    void subjectsIdDeleteSignalFull(OAIHttpRequestWorker *worker);
    void subjectsIdGetSignalFull(OAIHttpRequestWorker *worker, OAISubject summary);
    void subjectsIdPatchSignalFull(OAIHttpRequestWorker *worker, OAISubject summary);
    void subjectsPostSignalFull(OAIHttpRequestWorker *worker, OAISubject summary);
    void teachersGetSignalFull(OAIHttpRequestWorker *worker, OAIListTeachers summary);
    void teachersIdDeleteSignalFull(OAIHttpRequestWorker *worker);
    void teachersIdGetSignalFull(OAIHttpRequestWorker *worker, OAITeacher summary);
    void teachersIdPatchSignalFull(OAIHttpRequestWorker *worker, OAITeacher summary);
    void teachersPostSignalFull(OAIHttpRequestWorker *worker, OAITeacher summary);
    void timetablesGetSignalFull(OAIHttpRequestWorker *worker, OAIListTimetables summary);
    void timetablesIdDeleteSignalFull(OAIHttpRequestWorker *worker);
    void timetablesIdGetSignalFull(OAIHttpRequestWorker *worker, OAITimetable summary);
    void timetablesIdPatchSignalFull(OAIHttpRequestWorker *worker, OAITimetable summary);
    void timetablesPostSignalFull(OAIHttpRequestWorker *worker, OAITimetable summary);

    void errorsGetSignalError(OAIListErrors summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void errorsIdGetSignalError(OAIError summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void importPostSignalError(OAIListErrors summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void lessonsIdDeleteSignalError(QNetworkReply::NetworkError error_type, const QString &error_str);
    void lessonsIdGetSignalError(OAILesson summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void lessonsIdPatchSignalError(OAILesson summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void lessonsPostSignalError(OAILesson summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void lessonsTableIdGetSignalError(QList<OAILesson> summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void locationsGetSignalError(OAIListLocations summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void locationsIdDeleteSignalError(QNetworkReply::NetworkError error_type, const QString &error_str);
    void locationsIdGetSignalError(OAILocation summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void locationsIdPatchSignalError(OAILocation summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void locationsPostSignalError(OAILocation summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void subgroupsGetSignalError(OAIListSubgroups summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void subgroupsIdDeleteSignalError(QNetworkReply::NetworkError error_type, const QString &error_str);
    void subgroupsIdGetSignalError(OAISubgroup summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void subgroupsIdPatchSignalError(OAISubgroup summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void subgroupsPostSignalError(OAISubgroup summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void subjectsGetSignalError(OAIListSubjects summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void subjectsIdDeleteSignalError(QNetworkReply::NetworkError error_type, const QString &error_str);
    void subjectsIdGetSignalError(OAISubject summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void subjectsIdPatchSignalError(OAISubject summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void subjectsPostSignalError(OAISubject summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void teachersGetSignalError(OAIListTeachers summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void teachersIdDeleteSignalError(QNetworkReply::NetworkError error_type, const QString &error_str);
    void teachersIdGetSignalError(OAITeacher summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void teachersIdPatchSignalError(OAITeacher summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void teachersPostSignalError(OAITeacher summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void timetablesGetSignalError(OAIListTimetables summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void timetablesIdDeleteSignalError(QNetworkReply::NetworkError error_type, const QString &error_str);
    void timetablesIdGetSignalError(OAITimetable summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void timetablesIdPatchSignalError(OAITimetable summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void timetablesPostSignalError(OAITimetable summary, QNetworkReply::NetworkError error_type, const QString &error_str);

    void errorsGetSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void errorsIdGetSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void importPostSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void lessonsIdDeleteSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void lessonsIdGetSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void lessonsIdPatchSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void lessonsPostSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void lessonsTableIdGetSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void locationsGetSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void locationsIdDeleteSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void locationsIdGetSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void locationsIdPatchSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void locationsPostSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void subgroupsGetSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void subgroupsIdDeleteSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void subgroupsIdGetSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void subgroupsIdPatchSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void subgroupsPostSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void subjectsGetSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void subjectsIdDeleteSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void subjectsIdGetSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void subjectsIdPatchSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void subjectsPostSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void teachersGetSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void teachersIdDeleteSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void teachersIdGetSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void teachersIdPatchSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void teachersPostSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void timetablesGetSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void timetablesIdDeleteSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void timetablesIdGetSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void timetablesIdPatchSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void timetablesPostSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);

    void abortRequestsSignal();
    void allPendingRequestsCompleted();

public Q_SLOTS:
    void tokenAvailable();
};

} // namespace OpenAPI
#endif
