/**
 * pstu-timetable
 * pstu-timetable
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIListTimetables.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIListTimetables::OAIListTimetables(const QString &json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIListTimetables::OAIListTimetables() {
    this->initializeModel();
}

OAIListTimetables::~OAIListTimetables() {}

void OAIListTimetables::initializeModel() {

    m_pagination_isSet = false;
    m_pagination_isValid = false;

    m_timetables_isSet = false;
    m_timetables_isValid = false;
}

void OAIListTimetables::fromJson(const QString &jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIListTimetables::fromJsonObject(QJsonObject json) {

    m_pagination_isValid = ::OpenAPI::fromJsonValue(m_pagination, json[QString("pagination")]);
    m_pagination_isSet = !json[QString("pagination")].isNull() && m_pagination_isValid;

    m_timetables_isValid = ::OpenAPI::fromJsonValue(m_timetables, json[QString("timetables")]);
    m_timetables_isSet = !json[QString("timetables")].isNull() && m_timetables_isValid;
}

QString OAIListTimetables::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIListTimetables::asJsonObject() const {
    QJsonObject obj;
    if (m_pagination.isSet()) {
        obj.insert(QString("pagination"), ::OpenAPI::toJsonValue(m_pagination));
    }
    if (m_timetables.size() > 0) {
        obj.insert(QString("timetables"), ::OpenAPI::toJsonValue(m_timetables));
    }
    return obj;
}

OAIPagination OAIListTimetables::getPagination() const {
    return m_pagination;
}
void OAIListTimetables::setPagination(const OAIPagination &pagination) {
    m_pagination = pagination;
    m_pagination_isSet = true;
}

bool OAIListTimetables::is_pagination_Set() const{
    return m_pagination_isSet;
}

bool OAIListTimetables::is_pagination_Valid() const{
    return m_pagination_isValid;
}

QList<OAITimetable> OAIListTimetables::getTimetables() const {
    return m_timetables;
}
void OAIListTimetables::setTimetables(const QList<OAITimetable> &timetables) {
    m_timetables = timetables;
    m_timetables_isSet = true;
}

bool OAIListTimetables::is_timetables_Set() const{
    return m_timetables_isSet;
}

bool OAIListTimetables::is_timetables_Valid() const{
    return m_timetables_isValid;
}

bool OAIListTimetables::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_pagination.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_timetables.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIListTimetables::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_pagination_isValid && m_timetables_isValid && true;
}

} // namespace OpenAPI
