/**
 * pstu-timetable
 * pstu-timetable
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIListSubgroups.h
 *
 * 
 */

#ifndef OAIListSubgroups_H
#define OAIListSubgroups_H

#include <QJsonObject>

#include "OAIPagination.h"
#include "OAISubgroup.h"
#include <QList>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAIPagination;
class OAISubgroup;

class OAIListSubgroups : public OAIObject {
public:
    OAIListSubgroups();
    OAIListSubgroups(const QString &json);
    ~OAIListSubgroups() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(const QString &jsonString) override;

    OAIPagination getPagination() const;
    void setPagination(const OAIPagination &pagination);
    bool is_pagination_Set() const;
    bool is_pagination_Valid() const;

    QList<OAISubgroup> getSubgroups() const;
    void setSubgroups(const QList<OAISubgroup> &subgroups);
    bool is_subgroups_Set() const;
    bool is_subgroups_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    OAIPagination m_pagination;
    bool m_pagination_isSet;
    bool m_pagination_isValid;

    QList<OAISubgroup> m_subgroups;
    bool m_subgroups_isSet;
    bool m_subgroups_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIListSubgroups)

#endif // OAIListSubgroups_H
