/**
 * pstu-timetable
 * pstu-timetable
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIListTimetables.h
 *
 * 
 */

#ifndef OAIListTimetables_H
#define OAIListTimetables_H

#include <QJsonObject>

#include "OAIPagination.h"
#include "OAITimetable.h"
#include <QList>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAIPagination;
class OAITimetable;

class OAIListTimetables : public OAIObject {
public:
    OAIListTimetables();
    OAIListTimetables(const QString &json);
    ~OAIListTimetables() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(const QString &jsonString) override;

    OAIPagination getPagination() const;
    void setPagination(const OAIPagination &pagination);
    bool is_pagination_Set() const;
    bool is_pagination_Valid() const;

    QList<OAITimetable> getTimetables() const;
    void setTimetables(const QList<OAITimetable> &timetables);
    bool is_timetables_Set() const;
    bool is_timetables_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    OAIPagination m_pagination;
    bool m_pagination_isSet;
    bool m_pagination_isValid;

    QList<OAITimetable> m_timetables;
    bool m_timetables_isSet;
    bool m_timetables_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIListTimetables)

#endif // OAIListTimetables_H
