/**
 * pstu-timetable
 * pstu-timetable
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAILesson.h
 *
 * 
 */

#ifndef OAILesson_H
#define OAILesson_H

#include <QJsonObject>

#include "OAISubgroup.h"
#include "OAISubject.h"
#include "OAITeacherLocationAssignment.h"
#include "OAITimetable.h"
#include <QList>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAISubject;
class OAITimetable;
class OAITeacherLocationAssignment;
class OAISubgroup;

class OAILesson : public OAIObject {
public:
    OAILesson();
    OAILesson(const QString &json);
    ~OAILesson() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(const QString &jsonString) override;

    QString getId() const;
    void setId(const QString &id);
    bool is_id_Set() const;
    bool is_id_Valid() const;

    OAISubject getSubject() const;
    void setSubject(const OAISubject &subject);
    bool is_subject_Set() const;
    bool is_subject_Valid() const;

    QString getCategory() const;
    void setCategory(const QString &category);
    bool is_category_Set() const;
    bool is_category_Valid() const;

    qint32 getDay() const;
    void setDay(const qint32 &day);
    bool is_day_Set() const;
    bool is_day_Valid() const;

    qint32 getTimeStart() const;
    void setTimeStart(const qint32 &time_start);
    bool is_time_start_Set() const;
    bool is_time_start_Valid() const;

    qint32 getTimeEnd() const;
    void setTimeEnd(const qint32 &time_end);
    bool is_time_end_Set() const;
    bool is_time_end_Valid() const;

    qint32 getRepeatRule() const;
    void setRepeatRule(const qint32 &repeat_rule);
    bool is_repeat_rule_Set() const;
    bool is_repeat_rule_Valid() const;

    OAITimetable getTimetable() const;
    void setTimetable(const OAITimetable &timetable);
    bool is_timetable_Set() const;
    bool is_timetable_Valid() const;

    QList<OAITeacherLocationAssignment> getTeacherLocationAssignments() const;
    void setTeacherLocationAssignments(const QList<OAITeacherLocationAssignment> &teacher_location_assignments);
    bool is_teacher_location_assignments_Set() const;
    bool is_teacher_location_assignments_Valid() const;

    QList<OAISubgroup> getSubgroups() const;
    void setSubgroups(const QList<OAISubgroup> &subgroups);
    bool is_subgroups_Set() const;
    bool is_subgroups_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString m_id;
    bool m_id_isSet;
    bool m_id_isValid;

    OAISubject m_subject;
    bool m_subject_isSet;
    bool m_subject_isValid;

    QString m_category;
    bool m_category_isSet;
    bool m_category_isValid;

    qint32 m_day;
    bool m_day_isSet;
    bool m_day_isValid;

    qint32 m_time_start;
    bool m_time_start_isSet;
    bool m_time_start_isValid;

    qint32 m_time_end;
    bool m_time_end_isSet;
    bool m_time_end_isValid;

    qint32 m_repeat_rule;
    bool m_repeat_rule_isSet;
    bool m_repeat_rule_isValid;

    OAITimetable m_timetable;
    bool m_timetable_isSet;
    bool m_timetable_isValid;

    QList<OAITeacherLocationAssignment> m_teacher_location_assignments;
    bool m_teacher_location_assignments_isSet;
    bool m_teacher_location_assignments_isValid;

    QList<OAISubgroup> m_subgroups;
    bool m_subgroups_isSet;
    bool m_subgroups_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAILesson)

#endif // OAILesson_H
