/**
 * pstu-timetable
 * pstu-timetable
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIListLocations.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIListLocations::OAIListLocations(const QString &json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIListLocations::OAIListLocations() {
    this->initializeModel();
}

OAIListLocations::~OAIListLocations() {}

void OAIListLocations::initializeModel() {

    m_pagination_isSet = false;
    m_pagination_isValid = false;

    m_locations_isSet = false;
    m_locations_isValid = false;
}

void OAIListLocations::fromJson(const QString &jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIListLocations::fromJsonObject(QJsonObject json) {

    m_pagination_isValid = ::OpenAPI::fromJsonValue(m_pagination, json[QString("pagination")]);
    m_pagination_isSet = !json[QString("pagination")].isNull() && m_pagination_isValid;

    m_locations_isValid = ::OpenAPI::fromJsonValue(m_locations, json[QString("locations")]);
    m_locations_isSet = !json[QString("locations")].isNull() && m_locations_isValid;
}

QString OAIListLocations::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIListLocations::asJsonObject() const {
    QJsonObject obj;
    if (m_pagination.isSet()) {
        obj.insert(QString("pagination"), ::OpenAPI::toJsonValue(m_pagination));
    }
    if (m_locations.size() > 0) {
        obj.insert(QString("locations"), ::OpenAPI::toJsonValue(m_locations));
    }
    return obj;
}

OAIPagination OAIListLocations::getPagination() const {
    return m_pagination;
}
void OAIListLocations::setPagination(const OAIPagination &pagination) {
    m_pagination = pagination;
    m_pagination_isSet = true;
}

bool OAIListLocations::is_pagination_Set() const{
    return m_pagination_isSet;
}

bool OAIListLocations::is_pagination_Valid() const{
    return m_pagination_isValid;
}

QList<OAILocation> OAIListLocations::getLocations() const {
    return m_locations;
}
void OAIListLocations::setLocations(const QList<OAILocation> &locations) {
    m_locations = locations;
    m_locations_isSet = true;
}

bool OAIListLocations::is_locations_Set() const{
    return m_locations_isSet;
}

bool OAIListLocations::is_locations_Valid() const{
    return m_locations_isValid;
}

bool OAIListLocations::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_pagination.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_locations.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIListLocations::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_pagination_isValid && m_locations_isValid && true;
}

} // namespace OpenAPI
