/**
 * pstu-timetable
 * pstu-timetable
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIListTeachers.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIListTeachers::OAIListTeachers(const QString &json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIListTeachers::OAIListTeachers() {
    this->initializeModel();
}

OAIListTeachers::~OAIListTeachers() {}

void OAIListTeachers::initializeModel() {

    m_pagination_isSet = false;
    m_pagination_isValid = false;

    m_teachers_isSet = false;
    m_teachers_isValid = false;
}

void OAIListTeachers::fromJson(const QString &jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIListTeachers::fromJsonObject(QJsonObject json) {

    m_pagination_isValid = ::OpenAPI::fromJsonValue(m_pagination, json[QString("pagination")]);
    m_pagination_isSet = !json[QString("pagination")].isNull() && m_pagination_isValid;

    m_teachers_isValid = ::OpenAPI::fromJsonValue(m_teachers, json[QString("teachers")]);
    m_teachers_isSet = !json[QString("teachers")].isNull() && m_teachers_isValid;
}

QString OAIListTeachers::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIListTeachers::asJsonObject() const {
    QJsonObject obj;
    if (m_pagination.isSet()) {
        obj.insert(QString("pagination"), ::OpenAPI::toJsonValue(m_pagination));
    }
    if (m_teachers.size() > 0) {
        obj.insert(QString("teachers"), ::OpenAPI::toJsonValue(m_teachers));
    }
    return obj;
}

OAIPagination OAIListTeachers::getPagination() const {
    return m_pagination;
}
void OAIListTeachers::setPagination(const OAIPagination &pagination) {
    m_pagination = pagination;
    m_pagination_isSet = true;
}

bool OAIListTeachers::is_pagination_Set() const{
    return m_pagination_isSet;
}

bool OAIListTeachers::is_pagination_Valid() const{
    return m_pagination_isValid;
}

QList<OAITeacher> OAIListTeachers::getTeachers() const {
    return m_teachers;
}
void OAIListTeachers::setTeachers(const QList<OAITeacher> &teachers) {
    m_teachers = teachers;
    m_teachers_isSet = true;
}

bool OAIListTeachers::is_teachers_Set() const{
    return m_teachers_isSet;
}

bool OAIListTeachers::is_teachers_Valid() const{
    return m_teachers_isValid;
}

bool OAIListTeachers::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_pagination.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_teachers.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIListTeachers::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_pagination_isValid && m_teachers_isValid && true;
}

} // namespace OpenAPI
