/**
 * pstu-timetable
 * pstu-timetable
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIListSubjects.h
 *
 * 
 */

#ifndef OAIListSubjects_H
#define OAIListSubjects_H

#include <QJsonObject>

#include "OAIPagination.h"
#include "OAISubject.h"
#include <QList>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAIPagination;
class OAISubject;

class OAIListSubjects : public OAIObject {
public:
    OAIListSubjects();
    OAIListSubjects(const QString &json);
    ~OAIListSubjects() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(const QString &jsonString) override;

    OAIPagination getPagination() const;
    void setPagination(const OAIPagination &pagination);
    bool is_pagination_Set() const;
    bool is_pagination_Valid() const;

    QList<OAISubject> getSubjects() const;
    void setSubjects(const QList<OAISubject> &subjects);
    bool is_subjects_Set() const;
    bool is_subjects_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    OAIPagination m_pagination;
    bool m_pagination_isSet;
    bool m_pagination_isValid;

    QList<OAISubject> m_subjects;
    bool m_subjects_isSet;
    bool m_subjects_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIListSubjects)

#endif // OAIListSubjects_H
