/**
 * pstu-timetable
 * pstu-timetable
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAITimetable.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAITimetable::OAITimetable(const QString &json) {
    this->initializeModel();
    this->fromJson(json);
}

OAITimetable::OAITimetable() {
    this->initializeModel();
}

OAITimetable::~OAITimetable() {}

void OAITimetable::initializeModel() {

    m_id_isSet = false;
    m_id_isValid = false;

    m_name_isSet = false;
    m_name_isValid = false;

    m_date_start_isSet = false;
    m_date_start_isValid = false;

    m_date_end_isSet = false;
    m_date_end_isValid = false;

    m_week_isSet = false;
    m_week_isValid = false;
}

void OAITimetable::fromJson(const QString &jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAITimetable::fromJsonObject(QJsonObject json) {

    m_id_isValid = ::OpenAPI::fromJsonValue(m_id, json[QString("id")]);
    m_id_isSet = !json[QString("id")].isNull() && m_id_isValid;

    m_name_isValid = ::OpenAPI::fromJsonValue(m_name, json[QString("name")]);
    m_name_isSet = !json[QString("name")].isNull() && m_name_isValid;

    m_date_start_isValid = ::OpenAPI::fromJsonValue(m_date_start, json[QString("date_start")]);
    m_date_start_isSet = !json[QString("date_start")].isNull() && m_date_start_isValid;

    m_date_end_isValid = ::OpenAPI::fromJsonValue(m_date_end, json[QString("date_end")]);
    m_date_end_isSet = !json[QString("date_end")].isNull() && m_date_end_isValid;

    m_week_isValid = ::OpenAPI::fromJsonValue(m_week, json[QString("week")]);
    m_week_isSet = !json[QString("week")].isNull() && m_week_isValid;
}

QString OAITimetable::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAITimetable::asJsonObject() const {
    QJsonObject obj;
    if (m_id_isSet) {
        obj.insert(QString("id"), ::OpenAPI::toJsonValue(m_id));
    }
    if (m_name_isSet) {
        obj.insert(QString("name"), ::OpenAPI::toJsonValue(m_name));
    }
    if (m_date_start_isSet) {
        obj.insert(QString("date_start"), ::OpenAPI::toJsonValue(m_date_start));
    }
    if (m_date_end_isSet) {
        obj.insert(QString("date_end"), ::OpenAPI::toJsonValue(m_date_end));
    }
    if (m_week_isSet) {
        obj.insert(QString("week"), ::OpenAPI::toJsonValue(m_week));
    }
    return obj;
}

qint32 OAITimetable::getId() const {
    return m_id;
}
void OAITimetable::setId(const qint32 &id) {
    m_id = id;
    m_id_isSet = true;
}

bool OAITimetable::is_id_Set() const{
    return m_id_isSet;
}

bool OAITimetable::is_id_Valid() const{
    return m_id_isValid;
}

QString OAITimetable::getName() const {
    return m_name;
}
void OAITimetable::setName(const QString &name) {
    m_name = name;
    m_name_isSet = true;
}

bool OAITimetable::is_name_Set() const{
    return m_name_isSet;
}

bool OAITimetable::is_name_Valid() const{
    return m_name_isValid;
}

QDateTime OAITimetable::getDateStart() const {
    return m_date_start;
}
void OAITimetable::setDateStart(const QDateTime &date_start) {
    m_date_start = date_start;
    m_date_start_isSet = true;
}

bool OAITimetable::is_date_start_Set() const{
    return m_date_start_isSet;
}

bool OAITimetable::is_date_start_Valid() const{
    return m_date_start_isValid;
}

QDateTime OAITimetable::getDateEnd() const {
    return m_date_end;
}
void OAITimetable::setDateEnd(const QDateTime &date_end) {
    m_date_end = date_end;
    m_date_end_isSet = true;
}

bool OAITimetable::is_date_end_Set() const{
    return m_date_end_isSet;
}

bool OAITimetable::is_date_end_Valid() const{
    return m_date_end_isValid;
}

qint32 OAITimetable::getWeek() const {
    return m_week;
}
void OAITimetable::setWeek(const qint32 &week) {
    m_week = week;
    m_week_isSet = true;
}

bool OAITimetable::is_week_Set() const{
    return m_week_isSet;
}

bool OAITimetable::is_week_Valid() const{
    return m_week_isValid;
}

bool OAITimetable::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_name_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_date_start_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_date_end_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_week_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAITimetable::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_id_isValid && m_name_isValid && m_date_start_isValid && m_date_end_isValid && m_week_isValid && true;
}

} // namespace OpenAPI
