/**
 * pstu-timetable
 * pstu-timetable
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAITeacherLocationAssignment.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAITeacherLocationAssignment::OAITeacherLocationAssignment(const QString &json) {
    this->initializeModel();
    this->fromJson(json);
}

OAITeacherLocationAssignment::OAITeacherLocationAssignment() {
    this->initializeModel();
}

OAITeacherLocationAssignment::~OAITeacherLocationAssignment() {}

void OAITeacherLocationAssignment::initializeModel() {

    m_teacher_isSet = false;
    m_teacher_isValid = false;

    m_location_isSet = false;
    m_location_isValid = false;
}

void OAITeacherLocationAssignment::fromJson(const QString &jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAITeacherLocationAssignment::fromJsonObject(QJsonObject json) {

    m_teacher_isValid = ::OpenAPI::fromJsonValue(m_teacher, json[QString("teacher")]);
    m_teacher_isSet = !json[QString("teacher")].isNull() && m_teacher_isValid;

    m_location_isValid = ::OpenAPI::fromJsonValue(m_location, json[QString("location")]);
    m_location_isSet = !json[QString("location")].isNull() && m_location_isValid;
}

QString OAITeacherLocationAssignment::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAITeacherLocationAssignment::asJsonObject() const {
    QJsonObject obj;
    if (m_teacher.isSet()) {
        obj.insert(QString("teacher"), ::OpenAPI::toJsonValue(m_teacher));
    }
    if (m_location.isSet()) {
        obj.insert(QString("location"), ::OpenAPI::toJsonValue(m_location));
    }
    return obj;
}

OAITeacher OAITeacherLocationAssignment::getTeacher() const {
    return m_teacher;
}
void OAITeacherLocationAssignment::setTeacher(const OAITeacher &teacher) {
    m_teacher = teacher;
    m_teacher_isSet = true;
}

bool OAITeacherLocationAssignment::is_teacher_Set() const{
    return m_teacher_isSet;
}

bool OAITeacherLocationAssignment::is_teacher_Valid() const{
    return m_teacher_isValid;
}

OAILocation OAITeacherLocationAssignment::getLocation() const {
    return m_location;
}
void OAITeacherLocationAssignment::setLocation(const OAILocation &location) {
    m_location = location;
    m_location_isSet = true;
}

bool OAITeacherLocationAssignment::is_location_Set() const{
    return m_location_isSet;
}

bool OAITeacherLocationAssignment::is_location_Valid() const{
    return m_location_isValid;
}

bool OAITeacherLocationAssignment::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_teacher.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_location.isSet()) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAITeacherLocationAssignment::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_teacher_isValid && m_location_isValid && true;
}

} // namespace OpenAPI
